### PR TITLE
Register2016

### PR DESCRIPTION
**Pull request by rrone**
Updated:
- Look and feel to NG 2016
- Removed Schedule & Result menu items
- Updated assignor & system emails
- Updated graphics & favicon
- Updated app_dev.php to permit local domain for mobile testing on OS X
- Added gulpfile.js and ignore node_modules
   Should be sufficient for registration
   TO-DO: cerad_tourn_home route is not available

### CODE REVIEW

**Comment by ahundiak** [comment]
Not going to actually merge this into master as we want to keep the master branch setup for 2014.  The register2016 branch is basically the new master branch.

**Comment by rrone** [comment]
So I should branch off register2016 for any further changes?

rick roberts
Referee Administrator / AYSO Section 1
http://aysosection1.org

**Comment by ahundiak** [comment]
Yep. Though I don't think we need to do much more.  However, you do have a an extra comma after jquery in package.json that needs to be removed.  And /npm-log needs to be added to git ignore.

The styling looks good.  Kind of like to have a max width on the welcome page.  The buttons are way out to the margins on big monitors.  Maybe a bit more help explaining the ng2012/ng2014 referees just need to login in.  Maybe a forgot password link.  And of couse I'd like to see a Welcome/Home link in the left of the menu bar.  But I suspect that may be something that we may need to agree to disagree on.

And the big header image could be a link to the actual ayso national games site.

**Comment by rrone** [comment]
All good. 

I added some small border margin because the buttons & text ran to the edges on the mobiles.  

Did you catch the issue that the /home route is not working?  Something to fix?

I'll work in tomorrow.  Including the Welcome menu item.   

rick

**Comment by rrone** [comment]
Should i branch on register2016 or just make changes in that branch?

rick

**Comment by ahundiak** [comment]
You can make changes directly on the branch.

http://local.ng2014.zayso.org/home seems to be working as expected for me.

**Pull request closed without merging**
